schema: cell
name: ReRAM-2.5T1R-ISSCC16
cam_type: TCAM
memory_device: ./ReRAM-2.5T1R-ISSCC16.memory_device.yaml
layout:
  cell_process_node: 65nm
  area: 138.46F^2
  aspect_ratio: 9.0
ports:
  row:
    0:
      type: searchline
      connection:
        kind: access_device
        device: ./ReRAM-2.5T1R-ISSCC16.cmos_nmos_6F_gate.access_device.yaml
        count: 1
      wire_width: 2F
      voltages:
        set_lrs: 1.8V
        set_mrs: 1.8V
        reset: 1.2V
        search0: 1.1V
        search1: 0V
    1:
      type: searchline
      connection:
        kind: access_device
        device: ./ReRAM-2.5T1R-ISSCC16.cmos_pmos_3F_gate.access_device.yaml
        count: 1
      wire_width: 2F
      voltages:
        set_lrs: 0V
        set_mrs: 0V
        reset: 0V
        search0: 1.1V
        search1: 0V
    2:
      type: wordline
      connection:
        kind: access_device
        device: ./ReRAM-2.5T1R-ISSCC16.cmos_nmos_6F_gate.access_device.yaml
        count: 1
      wire_width: 2F
      voltages:
        set_lrs: 1.1V
        set_mrs: 1.1V
        reset: 1.1V
        search0: 1.1V
        search1: 1.1V
    3:
      type: sourceline
      connection:
        kind: access_device
        device: ./ReRAM-2.5T1R-ISSCC16.cmos_nmos_6F_drain.access_device.yaml
        count: 1
      wire_width: 2F
      voltages:
        set_lrs: 1.2V
        set_mrs: 1.2V
        reset: 1.8V
        search0: 1.1V
        search1: 0V
    4:
      type: wordline
      connection:
        kind: access_device
        device: ./ReRAM-2.5T1R-ISSCC16.cmos_nmos_6F_gate.access_device.yaml
        count: 1
      wire_width: 2F
      voltages:
        set_lrs: 1.1V
        set_mrs: 1.1V
        reset: 1.1V
        search0: 1.1V
        search1: 1.1V
    5:
      type: sourceline
      connection:
        kind: access_device
        device: ./ReRAM-2.5T1R-ISSCC16.cmos_nmos_0F_drain.access_device.yaml
        count: 1
      wire_width: 2F
      voltages:
        set_lrs: 1.2V
        set_mrs: 1.2V
        reset: 1.8V
        search0: 1.1V
        search1: 0V
  column:
    0:
      type: matchline
      connection:
        kind: access_device
        device: ./ReRAM-2.5T1R-ISSCC16.cmos_nmos_3F_drain.access_device.yaml
        count: 1
      wire_width: 1F
      voltages:
        set_lrs: 0V
        set_mrs: 0V
        reset: 0V
        search0: 1.1V
        search1: 1.1V
    1:
      type: bitline
      connection:
        kind: access_device
        device: ./ReRAM-2.5T1R-ISSCC16.cmos_nmos_6F_drain.access_device.yaml
        count: 1
      wire_width: 1F
      voltages:
        set_lrs: 0V
        set_mrs: 0V
        reset: 0V
        search0: 0V
        search1: 0V
    2:
      type: bitline
      connection:
        kind: memory_terminal
        terminal: drain
      wire_width: 1F
      voltages:
        set_lrs: 1.8V
        set_mrs: 1.8V
        reset: 1.8V
        search0: 1.1V
        search1: 1.1V
