# EvaCAM tool configuration: MRAM-4T2R-VLSIC12

architecture_file: ./MRAM-4T2R-VLSIC12_architecture_config.yaml
cell_file: ./MRAM-4T2R-VLSIC12_cell_config.yaml
optimization:
  target: ReadLatency
  buffer_design: latency
  row_driver: latency
  priority_encoder: latency
