schema: config
name: ReRAM-3T1R-ISSCC15
architecture: ReRAM-3T1R-ISSCC15.architecture.yaml
cell: ReRAM-3T1R-ISSCC15.cell.yaml
technology: ../lib/technology/cmos.legacy.yaml
optimization:
  target: ReadLatency
  buffer_design: latency
  row_driver: latency
  priority_encoder: latency
