schema: config
name: 2FeFET_TCAM_Area
architecture: 2FeFET_TCAM_512bit_fixed.architecture.yaml
cell: 2FeFET_TCAM_DSE.cell.yaml
technology: ../lib/technology/cmos.legacy.yaml
optimization:
  target: Area
  buffer_design: area
  row_driver: area
  priority_encoder: area
