# EvaCAM tool configuration: 2FeFET_TCAM_DSE

architecture_file: ./2FeFET_TCAM_DSE_architecture_config.yaml
cell_file: ./2FeFET_TCAM_DSE_cell_config.yaml
optimization:
  target: WriteLatency
  buffer_design: latency
  row_driver: latency
  priority_encoder: latency
