# EvaCAM tool configuration: 2FeFET_TCAM

architecture_file: ../2FeFET_TCAM_var_architecture_config.yaml
cell_file: ./2FeFET_TCAM_stdev03_cell_config.yaml
optimization:
  target: LeakagePower
  buffer_design: latency
  row_driver: latency
  priority_encoder: latency

output:
  yaml_file: results/variation_mc_sweep/2FeFET_TCAM_stdev03_results.yaml
