schema: config
name: 2FeFET_MCAM_as_TCAM
architecture: 2FeFET_MCAM.architecture.yaml
cell: 2FeFET_MCAM_as_TCAM.cell.yaml
technology: ../lib/technology/cmos.legacy.yaml
optimization:
  target: LeakagePower
  buffer_design: latency
  row_driver: latency
  priority_encoder: latency
