schema: architecture
design:
  target: CAM
  search_function: EX
  system_process_node: 22nm
  device_roadmap: HP
  temperature: 350K
memory:
  word_width: 64bits
routing:
  type: H-tree
peripherals:
  input:
    buffer: false
    encoder: false
    custom_encoder: false
  output:
    buffer: false
    priority_encoder: false
    accumulator: false
  write_driver: false
wires:
  local:
    type: LocalConservative
    repeater: RepeatedNone
    low_swing: false
  global:
    type: GlobalAggressive
    repeater: RepeatedNone
    low_swing: false
organization:
  banks:
    total: [1, 1]
    active: [1, 1]
  mats:
    total: [1, 1]
    active: [1, 1]
  subarray:
    dimensions: [64, 32]
  mux:
    sense_amp: 1
    output_level1: 1
    output_level2: 1
sensing: ./2FeFET_MCAM.sensing.yaml
matchline:
  additional_cap: 0fF
  match_transistor:
    cmos_width: 5F
