schema: config
name: 2FeFET_MCAM_10x256
architecture: 2FeFET_MCAM_10x256.architecture.yaml
cell: 2FeFET_MCAM.cell.yaml
technology: ../lib/technology/cmos.legacy.yaml
optimization:
  target: LeakagePower
  buffer_design: latency
  row_driver: latency
  priority_encoder: latency
