schema: cell
name: 2FeFET-MCAM-as-TCAM
cam_type: TCAM
memory_device: ./2FeFET_MCAM_as_TCAM.memory_device.yaml
layout:
  cell_process_node: 22nm
  area: 300F^2
  aspect_ratio: 1.76
ports:
  row:
    0:
      type: searchline
      connection:
        kind: memory_terminal
        terminal: gate
      wire_width: 1F
      voltages:
        set_lrs: 4V
        set_mrs: 4V
        reset: 4V
        search0: 1V
        search1: 1V
    1:
      type: searchline
      connection:
        kind: memory_terminal
        terminal: gate
      wire_width: 1F
      voltages:
        set_lrs: 4V
        set_mrs: 4V
        reset: 4V
        search0: 1V
        search1: 1V
  column:
    0:
      type: matchline
      connection:
        kind: memory_terminal
        terminal: drain
      wire_width: 1F
      voltages:
        set_lrs: 1V
        set_mrs: 1V
        reset: 1V
        search0: 0V
        search1: 1V
    1:
      type: matchline
      connection:
        kind: memory_terminal
        terminal: drain
      wire_width: 1F
      voltages:
        set_lrs: 1V
        set_mrs: 1V
        reset: 1V
        search0: 0V
        search1: 1V
