# EvaCAM tool configuration: 2FeFET_MCAM_as_TCAM

architecture_file: ./2FeFET_MCAM_architecture_config.yaml
cell_file: ./2FeFET_MCAM_as_TCAM_cell_config.yaml
optimization:
  target: LeakagePower
  buffer_design: latency
  row_driver: latency
  priority_encoder: latency
output:
  yaml_file: results/2FeFET_MCAM_as_TCAM_results.yaml
