# EvaCAM architecture configuration: 2FeFET_TCAM_explicit_subarray

design:
  target: CAM
  search_function: BE
  system_process_node: 45nm
  device_roadmap: HP
  temperature: 350K
memory:
  word_width: 64bits
routing:
  type: H-tree
peripherals:
  input:
    buffer: false
    encoder: false
    custom_encoder: false
  output:
    buffer: false
    priority_encoder: false
    accumulator: false
  write_driver: true
sensing:
  internal: true
  amplifier_type: nvsim_vol
wires:
  local:
    type: LocalConservative
    repeater: RepeatedNone
    low_swing: false
  global:
    type: GlobalAggressive
    repeater: RepeatedNone
    low_swing: false
organization:
  banks:
    total:
    - 1
    - 1
    active:
    - 1
    - 1
  mats:
    total:
    - 1
    - 1
    active:
    - 1
    - 1
  subarray:
    dimensions:
    - 64
    - 64
  mux:
    sense_amp: 1
    output_level1: 1
    output_level2: 1
matchline:
  additional_cap: 6fF
