# 2FeFET-TCAM System Configuration with 1000-sample Monte Carlo variation

design:
  target: CAM
  search_function: BE
  system_process_node: 45nm
  device_roadmap: HP
  temperature: 350K

memory:
  cell_file: ./config/2FeFET_TCAM/2FeFET_TCAM_mc1000_cell_config.yaml
  capacity: 512B
  word_width: 64bits

routing:
  type: H-tree

peripherals:
  input:
    buffer: false
    encoder: false
    custom_encoder: false
  output:
    buffer: false
    priority_encoder: false
    accumulator: false
  write_driver: true

sensing:
  internal: true
  amplifier_type: nvsim_vol
  custom_sense_amp: false

optimization:
  target: LeakagePower
  buffer_design: latency
  row_driver: latency
  priority_encoder: latency

wires:
  local:
    type: LocalConservative
    repeater: RepeatedNone
    low_swing: false
  global:
    type: GlobalAggressive
    repeater: RepeatedNone
    low_swing: false

organization:
  banks:
    total: [1, 1]
    active: [1, 1]
  mats:
    total: [1, 1]
    active: [1, 1]
  mux:
    sense_amp: 1
    output_level1: 1
    output_level2: 1

matchline:
  additional_cap: 6fF

extra:
  output_yaml_file: results/2FeFET_TCAM_mc1000_results.yaml
