schema: config
name: 2FeFET_TCAM_non_h_tree
architecture: 2FeFET_TCAM_non_h_tree.architecture.yaml
cell: 2FeFET_TCAM.cell.yaml
technology: ../lib/technology/cmos.legacy.yaml
optimization:
  target: SearchLatency
  buffer_design: latency
  row_driver: latency
  priority_encoder: latency
