schema: config
name: ReRAM-4T2R-VLSIC14
architecture: ReRAM-4T2R-VLSIC14.architecture.yaml
cell: ReRAM-4T2R-VLSIC14.cell.yaml
technology: ../lib/technology/cmos.legacy.yaml
optimization:
  target: ReadLatency
  buffer_design: latency
  row_driver: latency
  priority_encoder: latency
