schema: memory_device
name: ReRAM-4T2R-VLSIC14
type: memristor
resistance:
  'on': 400ohm
  'off': 300000ohm
read:
  mode: current
  current: 50uA
  power: 30uW
  min_sense_voltage: 25mV
write:
  set:
    mode: current
    current: 150uA
    pulse: 10ns
    energy: 1pJ
  reset:
    mode: current
    current: 150uA
    pulse: 10ns
    energy: 1pJ
