# FeFET-2Fe1T-DATE-2021 Cell Configuration
# Memory cell definition

cell:
  name: FeFET-2Fe1T-DATE-2021
  cam_type: TCAM
  type: FEFETRAM
  cell_process_node: 45nm
  area: 350F^2
  aspect_ratio: 1.76
access_device:
  type: cmos
  cmos_width: 1F
  voltage_drop: 0.15V
resistance:
  'on': 10000ohm
  'off': 1600000000ohm
read:
  mode: voltage
  power: 1uW
  min_sense_voltage: 70mV
write:
  set:
    mode: voltage
    voltage: 4V
    current: 5e-06uA
    pulse: 10ns
    energy: 2e-05pJ
  reset:
    mode: voltage
    voltage: 4V
    current: 5e-07uA
    pulse: 10ns
    energy: 2e-05pJ
multilevel:
  enabled: false
match:
  cmos_width: 10F
ports:
  row:
    0:
      type: searchline
      cmos_region: drain
      num_cmos: 1
      cmos_width: 1F
      is_nmos: true
      wire_width: 2F
      voltages:
        set_lrs: 0V
        set_mrs: 0V
        reset: 0V
        search0: 1V
        search1: 0V
    1:
      type: searchline
      cmos_region: drain
      num_cmos: 1
      cmos_width: 1F
      is_nmos: true
      wire_width: 2F
      voltages:
        set_lrs: 0V
        set_mrs: 0V
        reset: 0V
        search0: 0V
        search1: 1V
  column:
    0:
      type: matchline
      cmos_region: drain
      num_cmos: 1
      cmos_width: 1F
      is_nmos: true
      wire_width: 1F
      voltages:
        set_lrs: 0V
        set_mrs: 0V
        reset: 0V
        search0: 1V
        search1: 1V
    1:
      type: wordline
      cmos_region: gate
      num_cmos: 1
      cmos_width: 1F
      is_nmos: true
      wire_width: 1F
      voltages:
        set_lrs: 4V
        set_mrs: 4V
        reset: 4V
        search0: 1V
        search1: 1V
    2:
      type: wordline
      cmos_region: gate
      num_cmos: 1
      cmos_width: 1F
      is_nmos: true
      wire_width: 1F
      voltages:
        set_lrs: 4V
        set_mrs: 4V
        reset: 4V
        search0: 1V
        search1: 1V
