# EvaCAM architecture configuration: MRAM-2T2R-ASPDAC12

design:
  target: CAM
  search_function: EX
  system_process_node: 140nm
  device_roadmap: HP
  temperature: 350K
memory:
  capacity: 1152B
  word_width: 72bits
  physical_capacity: 9kb
routing:
  type: H-tree
peripherals:
  input:
    buffer: true
    encoder: false
    custom_encoder: false
  output:
    buffer: true
    priority_encoder: false
    accumulator: true
  write_driver: true
sensing:
  internal: true
  amplifier_type: nvsim_vol
wires:
  local:
    type: LocalConservative
    repeater: RepeatedNone
    low_swing: false
  global:
    type: GlobalAggressive
    repeater: RepeatedNone
    low_swing: false
organization:
  banks:
    total:
    - 1
    - 1
    active:
    - 1
    - 1
  mats:
    total:
    - 1
    - 1
    active:
    - 1
    - 1
  mux:
    sense_amp: 1
    output_level1: 1
    output_level2: 128
