schema: cell
name: SRAM-16T-ESSCIRC15
cam_type: TCAM
memory_device: ./SRAM-16T-ESSCIRC15.memory_device.yaml
access_device:
  type: cmos
  cmos_width: 1F
  voltage_drop: 0.15V
layout:
  cell_process_node: 28nm
  area: 1210F^2
  aspect_ratio: 3.51
ports:
  row:
    0:
      type: searchline
      cmos_region: gate
      num_cmos: 1
      cmos_width: 1F
      is_nmos: true
      wire_width: 1F
      voltages:
        set_lrs: 0V
        set_mrs: 0V
        reset: 0V
        search0: 0.9V
        search1: 0V
    1:
      type: searchline
      cmos_region: gate
      num_cmos: 1
      cmos_width: 1F
      is_nmos: true
      wire_width: 1F
      voltages:
        set_lrs: 0V
        set_mrs: 0V
        reset: 0V
        search0: 0V
        search1: 0.9V
    2:
      type: bitline
      cmos_region: drain
      num_cmos: 1
      cmos_width: 1F
      is_nmos: true
      wire_width: 1F
      voltages:
        set_lrs: 0.9V
        set_mrs: 0.9V
        reset: 0V
        search0: 0V
        search1: 0V
    3:
      type: bitline
      cmos_region: drain
      num_cmos: 1
      cmos_width: 1F
      is_nmos: true
      wire_width: 1F
      voltages:
        set_lrs: 0.9V
        set_mrs: 0.9V
        reset: 0V
        search0: 0V
        search1: 0V
  column:
    0:
      type: wordline
      cmos_region: gate
      num_cmos: 4
      cmos_width: 1F
      is_nmos: true
      wire_width: 1F
      voltages:
        set_lrs: 0.9V
        set_mrs: 0.9V
        reset: 0.9V
        search0: 0V
        search1: 0V
    1:
      type: matchline
      cmos_region: drain
      num_cmos: 2
      cmos_width: 1F
      is_nmos: true
      wire_width: 1F
      voltages:
        set_lrs: 0V
        set_mrs: 0V
        reset: 0V
        search0: 0V
        search1: 0V
